# Generated by Django 5.2.6 on 2026-03-07 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualifiedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_size_score', models.FloatField(default=0)),
                ('location_score', models.FloatField(default=0)),
                ('industry_score', models.FloatField(default=0)),
                ('phone_score', models.FloatField(default=0)),
                ('online_presence_score', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
                ('qualified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='scout.lead')),
            ],
            options={
                'db_table': 'qualified_leads',
            },
        ),
    ]
