# Generated by Django 5.2.6 on 2026-03-05 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeadJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_type", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("lead_number", models.IntegerField()),
                (
                    "email_style",
                    models.CharField(
                        choices=[
                            ("Friendly", "Friendly"),
                            ("Professional", "Professional"),
                            ("Simple", "Simple"),
                        ],
                        default="Professional",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "scout_lead_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("category", models.CharField(blank=True, default="", max_length=200)),
                ("website", models.URLField(blank=True, default="", max_length=500)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "email_address",
                    models.EmailField(blank=True, default="", max_length=255),
                ),
                ("address", models.TextField(blank=True, default="")),
                (
                    "cold_mail_status",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("send_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="scout.leadjob",
                    ),
                ),
            ],
            options={
                "db_table": "scout_leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
