# Generated by Django 5.2.6 on 2026-02-28 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('trial', 'Free Trial'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('duration_days', models.IntegerField(default=7)),
                ('can_flow_builder', models.BooleanField(default=True)),
                ('can_ai_agents', models.BooleanField(default=False)),
                ('can_api_access', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('can_team_members', models.BooleanField(default=False)),
                ('can_custom_agents', models.BooleanField(default=False)),
                ('can_ads_agent', models.BooleanField(default=False)),
                ('leads_limit', models.IntegerField(default=500)),
                ('campaigns_limit', models.IntegerField(default=1)),
                ('messages_limit', models.IntegerField(default=1000)),
                ('agents_limit', models.IntegerField(default=2)),
                ('team_limit', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='UsageTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leads_used', models.IntegerField(default=0)),
                ('campaigns_used', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('agents_active', models.IntegerField(default=0)),
                ('last_reset_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usage_trackers',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('trial', 'Trial'), ('pro', 'Pro'), ('enterprise', 'Enterprise'), ('admin', 'Admin')], default='trial', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.URLField(blank=True)),
                ('trial_started_at', models.DateTimeField(auto_now_add=True)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('razorpay_customer_id', models.CharField(blank=True, max_length=100)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
